/* Auto-generated by scrape_schedule.py */
/* Generated: 2026-05-06 15:00 UTC */

window.TMDB_OVERRIDES = window.TMDB_OVERRIDES || {};
window.TMDB_OVERRIDES["The Stranger"] = { id: 1429348 };

window.SCHEDULE = {

  /* =======================
   * Wednesday 6 May 2026
   * ======================= */
  "2026-05-06": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["19:00"] },
    { film: "Glenrothan", times: ["16:30"] },
    { film: "Michael", times: ["19:00"] },
    { film: "The Devil Wears Prada 2", times: ["16:30", "19:30"] },
  ],

  /* =======================
   * Thursday 7 May 2026
   * ======================= */
  "2026-05-07": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["19:30"] },
    { film: "Glenrothan", times: ["16:00"] },
    { film: "Michael", times: ["16:15", "19:00"] },
    { film: "NT Live: All My Sons", times: ["13:30"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Friday 8 May 2026
   * ======================= */
  "2026-05-08": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["16:00"] },
    { film: "Glenrothan", times: ["13:30"] },
    { film: "Michael", times: ["19:00"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "16:30", "19:30"] },
    { film: "The Sheep Detectives", times: ["13:00", "16:30", "19:00"] },
  ],

  /* =======================
   * Saturday 9 May 2026
   * ======================= */
  "2026-05-09": [
    { film: "Michael", times: ["19:00"] },
    { film: "NT Live: All My Sons", times: ["13:30"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "16:30", "19:30"] },
    { film: "The Sheep Detectives", times: ["14:00", "16:30", "19:00"] },
  ],

  /* =======================
   * Sunday 10 May 2026
   * ======================= */
  "2026-05-10": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["18:30"] },
    { film: "Dog Friendly Screening: The Devil Wears Paw-da 2", times: ["11:30"] },
    { film: "Michael", times: ["13:00"] },
    { film: "The Devil Wears Prada 2", times: ["12:45", "15:30", "18:30"] },
    { film: "The Sheep Detectives", times: ["14:15", "16:00", "18:00"] },
  ],

  /* =======================
   * Monday 11 May 2026
   * ======================= */
  "2026-05-11": [
    { film: "Glenrothan", times: ["13:15"] },
    { film: "Michael", times: ["16:00"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "16:15", "19:30"] },
    { film: "The Sheep Detectives", times: ["13:00", "16:00", "18:30"] },
  ],

  /* =======================
   * Tuesday 12 May 2026
   * ======================= */
  "2026-05-12": [
    { film: "Michael", times: ["19:30"] },
    { film: "The Devil Wears Prada 2", times: ["13:00", "16:30", "19:30"] },
    { film: "The Sheep Detectives", times: ["13:30", "17:00", "19:00"] },
  ],

  /* =======================
   * Wednesday 13 May 2026
   * ======================= */
  "2026-05-13": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["13:00"] },
    { film: "Michael", times: ["16:00"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "16:30", "19:30"] },
    { film: "The Sheep Detectives", times: ["14:00", "16:45", "19:15"] },
    { film: "Top Gun", times: ["19:30"] },
  ],

  /* =======================
   * Thursday 14 May 2026
   * ======================= */
  "2026-05-14": [
    { film: "Colours Of Time / La venue de l’avenir", times: ["16:30"] },
    { film: "Glenrothan", times: ["19:30"] },
    { film: "Michael", times: ["13:00"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["16:30"] },
    { film: "The Devil Wears Prada 2", times: ["13:30", "19:30"] },
    { film: "The Sheep Detectives", times: ["13:00", "16:00", "18:45"] },
  ],

  /* =======================
   * Friday 15 May 2026
   * ======================= */
  "2026-05-15": [
    { film: "Farming on the Edge", times: ["19:00"] },
    { film: "The Christophers", times: ["14:00", "19:45"] },
  ],

  /* =======================
   * Saturday 16 May 2026
   * ======================= */
  "2026-05-16": [
    { film: "The Christophers", times: ["16:00", "19:00"] },
  ],

  /* =======================
   * Sunday 17 May 2026
   * ======================= */
  "2026-05-17": [
    { film: "Funny Girl The Musical", times: ["18:00"] },
    { film: "The Christophers", times: ["13:30", "16:00"] },
  ],

  /* =======================
   * Monday 18 May 2026
   * ======================= */
  "2026-05-18": [
    { film: "The Christophers", times: ["13:30", "19:30"] },
  ],

  /* =======================
   * Tuesday 19 May 2026
   * ======================= */
  "2026-05-19": [
    { film: "Exhibition On Screen : FRIDA KAHLO", times: ["19:15"] },
    { film: "The Christophers", times: ["13:30", "16:15"] },
  ],

  /* =======================
   * Wednesday 20 May 2026
   * ======================= */
  "2026-05-20": [
    { film: "The Christophers", times: ["16:15", "19:30"] },
  ],

  /* =======================
   * Thursday 21 May 2026
   * ======================= */
  "2026-05-21": [
    { film: "Exhibition On Screen : FRIDA KAHLO", times: ["14:00"] },
    { film: "The Christophers", times: ["13:30", "19:30"] },
  ],

  /* =======================
   * Friday 22 May 2026
   * ======================= */
  "2026-05-22": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:00", "16:15", "19:30"] },
  ],

  /* =======================
   * Saturday 23 May 2026
   * ======================= */
  "2026-05-23": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:30", "16:00", "19:30"] },
  ],

  /* =======================
   * Sunday 24 May 2026
   * ======================= */
  "2026-05-24": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["12:30", "15:30", "18:30"] },
  ],

  /* =======================
   * Monday 25 May 2026
   * ======================= */
  "2026-05-25": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:15", "16:15", "19:30"] },
  ],

  /* =======================
   * Tuesday 26 May 2026
   * ======================= */
  "2026-05-26": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:00", "16:00", "19:30"] },
  ],

  /* =======================
   * Wednesday 27 May 2026
   * ======================= */
  "2026-05-27": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:30", "16:00", "19:30"] },
  ],

  /* =======================
   * Thursday 28 May 2026
   * ======================= */
  "2026-05-28": [
    { film: "NT Live: The Playboy of the Western World", times: ["19:30"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:00", "16:00"] },
  ],

  /* =======================
   * Friday 29 May 2026
   * ======================= */
  "2026-05-29": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["13:30", "19:30"] },
  ],

  /* =======================
   * Saturday 30 May 2026
   * ======================= */
  "2026-05-30": [
    { film: "Star Wars: The Mandalorian and Grogu", times: ["15:45", "19:30"] },
  ],

  /* =======================
   * Sunday 31 May 2026
   * ======================= */
  "2026-05-31": [
    { film: "NT Live: The Playboy of the Western World", times: ["14:00"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["18:30"] },
  ],

  /* =======================
   * Thursday 4 June 2026
   * ======================= */
  "2026-06-04": [
    { film: "Top Hat The Musical", times: ["19:30"] },
  ],

  /* =======================
   * Thursday 25 June 2026
   * ======================= */
  "2026-06-25": [
    { film: "NT Live: Les Liaisons Dangereuses", times: ["19:30"] },
  ],

  /* =======================
   * Sunday 28 June 2026
   * ======================= */
  "2026-06-28": [
    { film: "NT Live: Les Liaisons Dangereuses", times: ["14:00"] },
  ],

  /* =======================
   * Wednesday 1 July 2026
   * ======================= */
  "2026-07-01": [
  ],

  /* =======================
   * Saturday 4 July 2026
   * ======================= */
  "2026-07-01": [
    { film: "Evgenij Onegin – Tchaikovsky", times: ["19:15"] },
  ],

  "2026-07-04": [
    { film: "A Liberty of Conscience", times: ["16:00"] },
  ],
};
