/* Auto-generated by scrape_schedule.py — do not edit by hand */
/* Generated: 2026-04-01 09:53 UTC */

window.SCHEDULE = {

  /* =======================
   * Wednesday 1 April 2026
   * ======================= */
  "2026-04-01": [
    { film: "NT Live: The Playboy of the Western World", times: ["13:00", "16:00", "19:30"] },
    { film: "The Magic Faraway Tree", times: ["13:30", "16:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:00", "16:30", "19:30"] },
    { film: "on On Screen : FRIDA KAHLO", times: ["19:30"] },
  ],

  /* =======================
   * Thursday 2 April 2026
   * ======================= */
  "2026-04-02": [
    { film: "NT Live: The Playboy of the Western World", times: ["12:30", "16:00", "19:30"] },
    { film: "The Magic Faraway Tree", times: ["13:00", "16:00"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:30", "16:00", "18:45"] },
    { film: "on On Screen : FRIDA KAHLO", times: ["19:45"] },
  ],

  /* =======================
   * Friday 3 April 2026
   * ======================= */
  "2026-04-03": [
    { film: "NT Live: The Playboy of the Western World", times: ["15:45", "19:15"] },
    { film: "The Drama", times: ["19:25"] },
    { film: "The Magic Faraway Tree", times: ["13:00", "16:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:15", "16:00", "18:45"] },
  ],

  /* =======================
   * Saturday 4 April 2026
   * ======================= */
  "2026-04-04": [
    { film: "Midwinter Break", times: ["16:45"] },
    { film: "NT Live: The Playboy of the Western World", times: ["19:30"] },
    { film: "The Drama", times: ["19:30"] },
    { film: "The Magic Faraway Tree", times: ["14:15", "16:00"] },
    { film: "The Super Mario Galaxy Movie", times: ["16:30", "19:15"] },
    { film: "The Super Mario Galaxy Movie Autism Friendly Screening", times: ["14:00"] },
    { film: "on On Screen : FRIDA KAHLO", times: ["13:30"] },
  ],

  /* =======================
   * Sunday 5 April 2026
   * ======================= */
  "2026-04-05": [
    { film: "Dog Friendly Screening: The Devil Wears Paw-da 2", times: ["16:00"] },
    { film: "NT Live: The Playboy of the Western World", times: ["12:30", "18:00"] },
    { film: "The Drama", times: ["18:30"] },
    { film: "The Magic Faraway Tree", times: ["12:45", "15:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:30", "16:00", "18:00"] },
  ],

  /* =======================
   * Monday 6 April 2026
   * ======================= */
  "2026-04-06": [
    { film: "Midwinter Break", times: ["16:30"] },
    { film: "NT Live: The Playboy of the Western World", times: ["19:00"] },
    { film: "The Drama", times: ["19:30"] },
    { film: "The Magic Faraway Tree", times: ["12:30", "15:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:15", "16:00", "18:30"] },
    { film: "on On Screen : FRIDA KAHLO", times: ["13:00"] },
  ],

  /* =======================
   * Tuesday 7 April 2026
   * ======================= */
  "2026-04-07": [
    { film: "Midwinter Break", times: ["13:30"] },
    { film: "NT Live: The Playboy of the Western World", times: ["19:00"] },
    { film: "The Drama", times: ["19:30"] },
    { film: "The Magic Faraway Tree", times: ["13:00", "15:45"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:15", "16:15", "18:45"] },
    { film: "on On Screen : FRIDA KAHLO", times: ["16:30"] },
  ],

  /* =======================
   * Wednesday 8 April 2026
   * ======================= */
  "2026-04-08": [
    { film: "NT Live: The Playboy of the Western World", times: ["19:00"] },
    { film: "The Drama", times: ["19:30"] },
    { film: "The Magic Faraway Tree", times: ["13:45", "16:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:15", "16:00"] },
    { film: "The Super Mario Galaxy Movie Autism Friendly Screening", times: ["18:30"] },
  ],

  /* =======================
   * Thursday 9 April 2026
   * ======================= */
  "2026-04-09": [
    { film: "Midwinter Break", times: ["13:00"] },
    { film: "NT Live: The Playboy of the Western World", times: ["15:30", "19:00"] },
    { film: "The Drama", times: ["19:30"] },
    { film: "The Magic Faraway Tree", times: ["12:30", "16:30"] },
    { film: "The Super Mario Galaxy Movie", times: ["13:00", "16:00", "19:00"] },
  ],

  /* =======================
   * Thursday 16 April 2026
   * ======================= */
  "2026-04-16": [
    { film: "Mother�s Pride", times: ["19:30"] },
  ],

  /* =======================
   * Sunday 19 April 2026
   * ======================= */
  "2026-04-19": [
    { film: "Mother�s Pride", times: ["14:00"] },
  ],

  /* =======================
   * Tuesday 21 April 2026
   * ======================= */
  "2026-04-21": [
    { film: "MET Opera: Eugene Onegin", times: ["18:45"] },
  ],

  /* =======================
   * Sunday 26 April 2026
   * ======================= */
  "2026-04-26": [
    { film: "MET Opera: Eugene Onegin", times: ["14:00"] },
  ],

  /* =======================
   * Wednesday 29 April 2026
   * ======================= */
  "2026-04-29": [
    { film: "Dangereuses", times: ["19:30"] },
  ],

  /* =======================
   * Thursday 30 April 2026
   * ======================= */
  "2026-04-30": [
    { film: "Paw-da 2", times: ["19:30"] },
  ],

  /* =======================
   * Friday 1 May 2026
   * ======================= */
  "2026-05-01": [
    { film: "MET Opera: Eugene Onegin", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Saturday 2 May 2026
   * ======================= */
  "2026-05-02": [
    { film: "MET Opera: Eugene Onegin", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Sunday 3 May 2026
   * ======================= */
  "2026-05-03": [
    { film: "MET Opera: Eugene Onegin", times: ["12:30", "15:30", "18:30"] },
  ],

  /* =======================
   * Monday 4 May 2026
   * ======================= */
  "2026-05-04": [
    { film: "MET Opera: Eugene Onegin", times: ["12:30", "15:30", "19:00"] },
  ],

  /* =======================
   * Tuesday 5 May 2026
   * ======================= */
  "2026-05-05": [
    { film: "MET Opera: Eugene Onegin", times: ["18:00"] },
  ],

  /* =======================
   * Thursday 7 May 2026
   * ======================= */
  "2026-05-07": [
    { film: "MET Opera: Eugene Onegin", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Friday 8 May 2026
   * ======================= */
  "2026-05-08": [
    { film: "MET Opera: Eugene Onegin", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Saturday 9 May 2026
   * ======================= */
  "2026-05-09": [
    { film: "MET Opera: Eugene Onegin", times: ["13:30", "16:30", "19:30"] },
  ],

  /* =======================
   * Sunday 10 May 2026
   * ======================= */
  "2026-05-10": [
    { film: "Dog Friendly Screening: The Devil Wears Paw-da 2", times: ["11:30"] },
    { film: "MET Opera: Eugene Onegin", times: ["15:30", "18:30"] },
  ],

  /* =======================
   * Tuesday 19 May 2026
   * ======================= */
  "2026-05-19": [
    { film: "Dog Friendly Screening: The Devil Wears Paw-da 2", times: ["19:15"] },
  ],

  /* =======================
   * Thursday 21 May 2026
   * ======================= */
  "2026-05-21": [
    { film: "Dog Friendly Screening: The Devil Wears Paw-da 2", times: ["14:00"] },
  ],

  /* =======================
   * Thursday 28 May 2026
   * ======================= */
  "2026-05-28": [
    { film: "ve: All My Sons", times: ["19:30"] },
  ],

  /* =======================
   * Sunday 31 May 2026
   * ======================= */
  "2026-05-31": [
    { film: "ve: All My Sons", times: ["14:00"] },
  ],

  /* =======================
   * Thursday 25 June 2026
   * ======================= */
  "2026-06-25": [
    { film: "NT Live: All My Sons", times: ["19:30"] },
  ],

  /* =======================
   * Sunday 28 June 2026
   * ======================= */
  "2026-06-28": [
    { film: "NT Live: All My Sons", times: ["14:00"] },
  ],
};
