/* Auto-generated by scrape_schedule.py */
/* Generated: 2026-06-09 08:25 UTC */

window.TMDB_OVERRIDES = window.TMDB_OVERRIDES || {};
window.TMDB_OVERRIDES["The Stranger"] = { id: 1429348 };

window.SCHEDULE = {

  /* =======================
   * Tuesday 9 June 2026
   * ======================= */
  "2026-06-09": [
    { film: "My Mother's Wedding", times: ["16:30", "19:30"] },
    { film: "Savage House", times: ["13:30", "19:30"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["19:00"] },
    { film: "The Sheep Detectives", times: ["17:00"] },
    { film: "Tuner", times: ["13:30", "16:15"] },
  ],

  /* =======================
   * Wednesday 10 June 2026
   * ======================= */
  "2026-06-10": [
    { film: "Disclosure Day", times: ["13:00", "16:30", "19:30"] },
    { film: "Moss & Freud", times: ["13:00"] },
    { film: "Savage House", times: ["19:45"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["19:30"] },
    { film: "The Sheep Detectives", times: ["17:00"] },
    { film: "Tuner", times: ["13:30", "16:15"] },
  ],

  /* =======================
   * Thursday 11 June 2026
   * ======================= */
  "2026-06-11": [
    { film: "Disclosure Day", times: ["12:30", "16:00", "19:30"] },
    { film: "Moss & Freud", times: ["16:00"] },
    { film: "My Mother's Wedding", times: ["13:30"] },
    { film: "Savage House", times: ["19:00"] },
    { film: "Star Wars: The Mandalorian and Grogu", times: ["19:30"] },
    { film: "Tuner", times: ["13:00", "16:00"] },
  ],

  /* =======================
   * Friday 12 June 2026
   * ======================= */
  "2026-06-12": [
    { film: "Disclosure Day", times: ["13:00", "16:00", "19:30"] },
    { film: "Savage House", times: ["19:30"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["13:30", "19:15"] },
    { film: "The Sheep Detectives", times: ["16:45"] },
    { film: "Tuner", times: ["16:30"] },
  ],

  /* =======================
   * Saturday 13 June 2026
   * ======================= */
  "2026-06-13": [
    { film: "Disclosure Day", times: ["12:30", "16:00", "19:30"] },
    { film: "My Mother's Wedding", times: ["16:30"] },
    { film: "Savage House", times: ["19:30"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["16:00", "19:00"] },
    { film: "The Sheep Detectives", times: ["13:30"] },
    { film: "Tuner", times: ["13:00"] },
  ],

  /* =======================
   * Sunday 14 June 2026
   * ======================= */
  "2026-06-14": [
    { film: "Disclosure Day", times: ["12:30", "15:00", "18:15"] },
    { film: "My Mother's Wedding", times: ["13:00"] },
    { film: "Savage House", times: ["15:30"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["16:00", "18:30"] },
    { film: "The Sheep Detectives", times: ["12:30", "18:30"] },
  ],

  /* =======================
   * Monday 15 June 2026
   * ======================= */
  "2026-06-15": [
    { film: "Disclosure Day", times: ["13:00", "16:15", "19:30"] },
    { film: "My Mother's Wedding", times: ["19:45"] },
    { film: "Savage House", times: ["14:00"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["13:30", "16:30", "19:30"] },
    { film: "Tuner", times: ["17:00"] },
  ],

  /* =======================
   * Tuesday 16 June 2026
   * ======================= */
  "2026-06-16": [
    { film: "Disclosure Day", times: ["13:30", "16:30", "19:30"] },
    { film: "My Mother's Wedding", times: ["19:45"] },
    { film: "Savage House", times: ["19:30"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["14:00"] },
    { film: "The Sheep Detectives", times: ["17:00"] },
  ],

  /* =======================
   * Wednesday 17 June 2026
   * ======================= */
  "2026-06-17": [
    { film: "Disclosure Day", times: ["13:00", "16:15", "19:30"] },
    { film: "Savage House", times: ["15:30"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["14:00", "19:30"] },
    { film: "The Sheep Detectives", times: ["16:45"] },
    { film: "Tuner", times: ["19:00"] },
  ],

  /* =======================
   * Thursday 18 June 2026
   * ======================= */
  "2026-06-18": [
    { film: "Disclosure Day", times: ["13:00", "15:30", "19:00"] },
    { film: "Savage House", times: ["16:00"] },
    { film: "The Fall of Sir Douglas Weatherford", times: ["13:30", "19:30"] },
    { film: "Toy Story 5", times: ["17:00", "19:30"] },
  ],

  /* =======================
   * Friday 19 June 2026
   * ======================= */
  "2026-06-19": [
    { film: "Toy Story 5", times: ["13:30", "17:00", "19:00"] },
  ],

  /* =======================
   * Saturday 20 June 2026
   * ======================= */
  "2026-06-20": [
    { film: "Toy Story 5", times: ["13:30", "16:30", "19:15"] },
  ],

  /* =======================
   * Sunday 21 June 2026
   * ======================= */
  "2026-06-21": [
    { film: "Toy Story 5", times: ["12:45", "15:30", "18:15"] },
  ],

  /* =======================
   * Monday 22 June 2026
   * ======================= */
  "2026-06-22": [
    { film: "Toy Story 5", times: ["13:30", "16:45", "19:00"] },
  ],

  /* =======================
   * Tuesday 23 June 2026
   * ======================= */
  "2026-06-23": [
    { film: "Toy Story 5", times: ["13:00", "16:45", "19:00"] },
  ],

  /* =======================
   * Wednesday 24 June 2026
   * ======================= */
  "2026-06-24": [
    { film: "Toy Story 5", times: ["13:00", "17:00", "19:00"] },
  ],

  /* =======================
   * Thursday 25 June 2026
   * ======================= */
  "2026-06-25": [
    { film: "NT Live: Les Liaisons Dangereuses", times: ["19:30"] },
    { film: "Toy Story 5", times: ["16:30"] },
  ],

  /* =======================
   * Friday 26 June 2026
   * ======================= */
  "2026-06-26": [
    { film: "Supergirl", times: ["13:30", "16:00", "19:30"] },
    { film: "Toy Story 5", times: ["14:00", "16:30", "19:00"] },
  ],

  /* =======================
   * Saturday 27 June 2026
   * ======================= */
  "2026-06-27": [
    { film: "Supergirl", times: ["13:00", "16:30", "19:30"] },
    { film: "Toy Story 5", times: ["13:30", "16:15", "19:00"] },
  ],

  /* =======================
   * Sunday 28 June 2026
   * ======================= */
  "2026-06-28": [
    { film: "NT Live: Les Liaisons Dangereuses", times: ["14:00"] },
    { film: "Supergirl", times: ["13:30", "17:30"] },
    { film: "Toy Story 5", times: ["13:30", "17:00"] },
  ],

  /* =======================
   * Monday 29 June 2026
   * ======================= */
  "2026-06-29": [
    { film: "Supergirl", times: ["13:45", "16:30", "19:15"] },
    { film: "Toy Story 5", times: ["13:30", "16:30", "19:15"] },
  ],

  /* =======================
   * Tuesday 30 June 2026
   * ======================= */
  "2026-06-30": [
    { film: "Supergirl", times: ["13:30", "16:15", "19:15"] },
    { film: "Toy Story 5", times: ["13:30", "16:30", "19:00"] },
  ],

  /* =======================
   * Wednesday 1 July 2026
   * ======================= */
  "2026-07-01": [
    { film: "Minions & Monsters", times: ["16:30"] },
    { film: "Supergirl", times: ["13:30", "16:30", "19:30"] },
    { film: "Teatro alla Scala", times: ["19:15"] },
    { film: "Toy Story 5", times: ["13:00", "16:00", "19:00"] },
  ],

  /* =======================
   * Thursday 2 July 2026
   * ======================= */
  "2026-07-02": [
    { film: "Minions & Monsters", times: ["13:00", "16:30", "19:00"] },
    { film: "Supergirl", times: ["13:30", "16:00", "19:00"] },
    { film: "Toy Story 5", times: ["13:00", "16:00", "19:15"] },
  ],

  /* =======================
   * Saturday 4 July 2026
   * ======================= */
  "2026-07-04": [
    { film: "A Liberty of Conscience", times: ["16:00"] },
  ],

  /* =======================
   * Wednesday 5 August 2026
   * ======================= */
  "2026-08-05": [
    { film: "Teatro dellOpera di Roma", times: ["19:15"] },
  ],

  /* =======================
   * Saturday 8 August 2026
   * ======================= */
  "2026-08-08": [
    { film: "Concert", times: ["16:00"] },
  ],

  /* =======================
   * Sunday 9 August 2026
   * ======================= */
  "2026-08-09": [
    { film: "Concert", times: ["14:00"] },
  ],

  /* =======================
   * Saturday 22 August 2026
   * ======================= */
  "2026-08-22": [
    { film: "Live Performance", times: ["10:00"] },
  ],

  /* =======================
   * Wednesday 2 September 2026
   * ======================= */
  "2026-09-02": [
    { film: "Cosi Fan Tutte  Mozart", times: ["19:30"] },
  ],
};
