#!/usr/bin/env python3
"""
Scrapes https://www.stationcinema.com/whatson/all

Raw HTML structure (after stripping tags):
  Showtimes
  Film Title (mixed case)
  Running time: N mins
  Genre1, Genre2
  Friday 17 April 2026 13:30 19:30 Saturday 18 April 2026 16:30  <- all on ONE line
  [duplicate of above]
  Next Film Title
"""
import re, urllib.request, sys
from datetime import datetime
from collections import defaultdict

URL = "https://www.stationcinema.com/whatson/all"
MONTHS = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,
          "july":7,"august":8,"september":9,"october":10,"november":11,"december":12}
MONTH_NAMES = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]
GENRE_WORDS = frozenset([
    "drama","comedy","music","family","adventure","animation","thriller",
    "romance","documentary","biography","musical","theatre","play","opera",
    "fantasy","biopic","action","mystery","science","fiction","romantic",
    "teatro","nation","live","sci-fi","horror","crime","historical",
    "war","sport","western","noir","suspense","supernatural",
    "psychological","political","satire","parody"
])
ALWAYS_SKIP = re.compile(
    r"^(Showtimes|Running time:|Check Our Socials|About Us|Stay connected|"
    r"TikTok|Membership|Private Hire|Gaming|Contact|Gift|Get in Touch|"
    r"Latest News|Now Showing|Coming Soon|Live Events|Senior Screenings|"
    r"Subtitled Screenings|Selects|Dog Friendly$).*",
    re.IGNORECASE
)
DATE_IN_LINE = re.compile(
    r"(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)"
    r"\s+(\d{1,2})\s+"
    r"(January|February|March|April|May|June|July|August|"
    r"September|October|November|December)\s+(\d{4})",
    re.IGNORECASE
)
TIME_PAT = re.compile(r"\b(\d{1,2}:\d{2})\b")

def is_genre_line(line):
    cleaned = re.sub(r"[^a-z ]", " ", line.lower())
    words = set(cleaned.split())
    words.discard("")
    return bool(words) and words.issubset(GENRE_WORDS)

def parse_date_time_line(line):
    result = defaultdict(set)
    matches = list(DATE_IN_LINE.finditer(line))
    for i, m in enumerate(matches):
        month = MONTHS.get(m.group(3).lower(), 0)
        if not month:
            continue
        date_key = f"{int(m.group(4)):04d}-{month:02d}-{int(m.group(2)):02d}"
        seg_end = matches[i+1].start() if i+1 < len(matches) else len(line)
        segment = line[m.end():seg_end]
        for t in TIME_PAT.findall(segment):
            result[date_key].add(t)
    return result

def fetch_page():
    req = urllib.request.Request(URL, headers={
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    })
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
        print(f"HTTP {resp.status}, {len(data)} bytes")
        return data.decode("utf-8", errors="replace")

def strip_html(html):
    html = re.sub(r"<script[^>]*>.*?</script>", " ", html, flags=re.S)
    html = re.sub(r"<style[^>]*>.*?</style>", " ", html, flags=re.S)
    html = re.sub(r"<br\s*/?>", "\n", html, flags=re.I)
    html = re.sub(r"<[^>]+>", " ", html)
    html = re.sub(r"&amp;", "&", html)
    html = re.sub(r"&ndash;|&#8211;|&#x2013;", "-", html)
    html = re.sub(r"&[a-z#0-9]+;", " ", html)
    html = re.sub(r"[ \t]+", " ", html)
    html = re.sub(r"[ ]*[\r\n]+[ ]*", "\n", html)
    html = re.sub(r"\n{2,}", "\n", html)
    return html.strip()

def extract_showtimes(html):
    soldout_idx = html.find("soldOutOverride")
    start = html.find("Showtimes", soldout_idx if soldout_idx > 0 else 0)
    if start == -1:
        print("ERROR: Cannot find Showtimes section")
        return {}
    end_markers = ["Check Our Socials", "About Us", "Restoration Levy"]
    end = len(html)
    for marker in end_markers:
        idx = html.find(marker, start)
        if idx > 0:
            end = min(end, idx)
    section = html[start:end]
    text = strip_html(section)
    print(f"Section: {len(text)} chars")
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    print(f"Lines: {len(lines)}")
    schedule = defaultdict(lambda: defaultdict(set))
    current_film = None
    seen_lines = set()
    for line in lines:
        if ALWAYS_SKIP.match(line):
            continue
        if is_genre_line(line):
            continue
        if DATE_IN_LINE.search(line):
            if current_film and line not in seen_lines:
                seen_lines.add(line)
                for date_key, times in parse_date_time_line(line).items():
                    for t in times:
                        schedule[date_key][current_film].add(t)
            continue
        if len(line) < 3:
            continue
        current_film = line
        seen_lines = set()
        print(f"  Film: {current_film}")
    return schedule

def render_js(schedule):
    lines = [
        "/* Auto-generated by scrape_schedule.py */",
        f"/* Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} */",
        "",
        "window.TMDB_OVERRIDES = window.TMDB_OVERRIDES || {};",
        'window.TMDB_OVERRIDES["The Stranger"] = { id: 1429348 };',
        "",
        "window.SCHEDULE = {"
    ]
    for date_key in sorted(schedule.keys()):
        dt = datetime.strptime(date_key, "%Y-%m-%d")
        lines += ["", "  /* =======================",
                  f"   * {dt.strftime('%A')} {dt.day} {MONTH_NAMES[dt.month-1]} {dt.year}",
                  "   * ======================= */", f'  "{date_key}": [']
        for film, times_set in sorted(schedule[date_key].items()):
            ts = ", ".join(f'"{t}"' for t in sorted(times_set))
            lines.append(f'    {{ film: "{film}", times: [{ts}] }},')
        lines.append("  ],")
    lines += ["};", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    print(f"Fetching {URL}")
    html = fetch_page()
    print(f"Page: {len(html)} chars")
    schedule = extract_showtimes(html)
    if not schedule:
        print("WARNING: No schedule data found — keeping existing schedule.js")
        sys.exit(1)
    total = sum(len(v) for v in schedule.values())
    print(f"Found {total} showings across {len(schedule)} days")
    with open("schedule.js", "w", encoding="utf-8") as f:
        f.write(render_js(schedule))
    print("Done")
