#!/usr/bin/env python3
"""
Scrapes https://www.stationcinema.com/whatson/all
The page renders showtime data in the raw HTML (not via JS).
Runs every Wednesday via GitHub Actions.
"""
import re, urllib.request
from datetime import datetime
from collections import defaultdict

URL = "https://www.stationcinema.com/whatson/all"
MONTHS = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,
          "july":7,"august":8,"september":9,"october":10,"november":11,"december":12}
MONTH_NAMES = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]

def fetch_page():
    req = urllib.request.Request(URL, headers={
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-GB,en;q=0.5",
    })
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", errors="replace")

def extract_showtimes(html):
    # Strip scripts and styles
    html = re.sub(r'<script[^>]*>.*?</script>', ' ', html, flags=re.S)
    html = re.sub(r'<style[^>]*>.*?</style>', ' ', html, flags=re.S)
    # Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', html)
    text = re.sub(r'&amp;', '&', text)
    text = re.sub(r'&[a-z#0-9]+;', ' ', text)
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n+', '\n', text)

    print(f"Text length after strip: {len(text)}")

    # Debug: find key markers
    for marker in ['Showtimes', 'Running time', 'Check Our Socials', 'soldOut', 'whatson']:
        idx = text.find(marker)
        print(f"Marker '{marker}' at position: {idx}")
        if idx > 0:
            print(f"  Context: {repr(text[max(0,idx-30):idx+50])}")

    schedule = defaultdict(lambda: defaultdict(set))

    # The page structure: film title appears before each "Running time: N mins" block
    # Find all Running time occurrences
    rt_positions = [m.start() for m in re.finditer(r'Running time:', text, re.IGNORECASE)]
    print(f"Found {len(rt_positions)} 'Running time:' occurrences")

    if not rt_positions:
        return {}

    date_pat = re.compile(
        r'(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)'
        r'\s+(\d{1,2})\s+'
        r'(January|February|March|April|May|June|July|August|September|October|November|December)'
        r'\s+(\d{4})'
        r'((?:\s*\d{1,2}:\d{2})+)',
        re.IGNORECASE
    )

    skip = re.compile(
        r'^(Running|Now Showing|Coming Soon|Live Events|Senior|Subtitled|'
        r'Latest News|Membership|Private Hire|Gaming|Contact|Gift|Get in Touch|'
        r'Stay connected|About|FAQ|Telephone|Restoration|Charity|RECEIVE|TikTok|'
        r'Drama|Comedy|Music$|Family$|Adventure$|Animation$|Thriller$|Romance$|'
        r'Documentary$|Biography$|Musical$|Theatre$|Play$|Opera$|Nation|Biopic|'
        r'Science Fiction|Romantic|Fantasy|Monday|Tuesday|Wednesday|Thursday|'
        r'Friday|Saturday|Sunday|\d)',
        re.IGNORECASE
    )

    for i, pos in enumerate(rt_positions):
        # Get the block AFTER this "Running time:"
        end_pos = rt_positions[i+1] if i+1 < len(rt_positions) else pos + 5000
        block = text[pos:end_pos]

        # Get film title from text BEFORE this "Running time:"
        start_of_prev = rt_positions[i-1] + 200 if i > 0 else 0
        preceding = text[start_of_prev:pos]

        # Get last meaningful line before "Running time:"
        lines = [l.strip() for l in preceding.replace('\r','\n').split('\n') if l.strip()]
        film = None
        for line in reversed(lines):
            if len(line) < 2 or re.match(r'^[\d:]+$', line) or skip.match(line):
                continue
            film = line
            break

        if not film:
            continue

        # Find dates and times in this block
        seen = set()
        for m in date_pat.finditer(block):
            date_key = f"{int(m.group(4)):04d}-{MONTHS.get(m.group(3).lower(),0):02d}-{int(m.group(2)):02d}"
            if not MONTHS.get(m.group(3).lower()):
                continue
            times = re.findall(r'\b(\d{1,2}:\d{2})\b', m.group(5))
            key = (date_key, frozenset(times))
            if key in seen:
                continue
            seen.add(key)
            for t in times:
                schedule[date_key][film].add(t)

    return schedule

def render_js(schedule):
    lines = [
        "/* Auto-generated by scrape_schedule.py */",
        f"/* Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} */",
        "",
        "window.TMDB_OVERRIDES = window.TMDB_OVERRIDES || {};",
        'window.TMDB_OVERRIDES["The Stranger"] = { id: 1429348 };',
        "",
        "window.SCHEDULE = {"
    ]
    for date_key in sorted(schedule.keys()):
        dt = datetime.strptime(date_key, "%Y-%m-%d")
        lines += [
            "",
            "  /* =======================",
            f"   * {dt.strftime('%A')} {dt.day} {MONTH_NAMES[dt.month-1]} {dt.year}",
            "   * ======================= */",
            f'  "{date_key}": ['
        ]
        for film, times_set in sorted(schedule[date_key].items()):
            ts = ", ".join(f'"{t}"' for t in sorted(times_set))
            lines.append(f'    {{ film: "{film}", times: [{ts}] }},')
        lines.append("  ],")
    lines += ["};", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    print("Fetching", URL)
    html = fetch_page()
    print(f"Page fetched: {len(html)} chars")
    schedule = extract_showtimes(html)
    if not schedule:
        print("WARNING: No schedule data found — keeping existing schedule.js")
        raise SystemExit(1)
    total = sum(len(v) for v in schedule.values())
    print(f"Found {total} film/day combinations across {len(schedule)} days")
    output = render_js(schedule)
    with open("schedule.js", "w", encoding="utf-8") as f:
        f.write(output)
    print("schedule.js written successfully")
