#!/usr/bin/env python3
"""
Scrapes https://www.stationcinema.com/whatson/all
and writes schedule.js for the Station Cinema signage board.
Run automatically every Wednesday by GitHub Actions.
"""
import re, urllib.request
from datetime import datetime
from collections import defaultdict

URL = "https://www.stationcinema.com/whatson/all"
MONTHS = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,
          "july":7,"august":8,"september":9,"october":10,"november":11,"december":12}
MONTH_NAMES = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]

def fetch_page():
    req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read().decode("utf-8", errors="replace")

def parse_date(day, month_name, year):
    month = MONTHS.get(month_name.lower())
    if not month: return None
    return f"{int(year):04d}-{month:02d}-{int(day):02d}"

def extract_showtimes(html):
    # Strip scripts and styles first
    html = re.sub(r'<script[^>]*>.*?</script>', ' ', html, flags=re.S)
    html = re.sub(r'<style[^>]*>.*?</style>', ' ', html, flags=re.S)
    # Extract just the showtimes section between "Showtimes" and "Check Our Socials"
    m = re.search(r'Showtimes(.+?)Check Our Socials', html, re.S)
    if not m:
        print("WARNING: Could not find Showtimes section")
        return {}
    body = m.group(1)
    # Remove all HTML tags
    body = re.sub(r'<[^>]+>', ' ', body)
    body = re.sub(r'&amp;', '&', body)
    body = re.sub(r'&[a-z#0-9]+;', ' ', body)
    body = re.sub(r'[ \t]+', ' ', body)
    # Normalise line breaks
    body = re.sub(r'\n+', '\n', body.replace('\r', '\n'))

    schedule = defaultdict(lambda: defaultdict(set))

    # Each film block starts with the film title on its own line,
    # followed by "Running time: N mins", then genre, then date+time lines.
    # Split on "Running time:" to get blocks, film title precedes each block.
    # We process the full text linearly.
    lines = [l.strip() for l in body.split('\n') if l.strip()]

    # Known non-title lines to skip
    skip_patterns = re.compile(
        r'^(Running time:|\d|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|'
        r'Drama|Comedy|Music|Family|Adventure|Animation|Thriller|Romance|Documentary|'
        r'Biography|Musical|Theatre|Play|Opera|Science|Fiction|Romantic|Fantasy|'
        r'Now Showing|Coming Soon|Live Events|Senior|Subtitled|Latest|Membership|'
        r'Private|Gaming|Contact|Gift|Get in Touch|Stay connected|About|FAQ|'
        r'Telephone|Station Cinema|Restoration|Charity|RECEIVE|TikTok)',
        re.I
    )

    current_film = None
    date_time_pat = re.compile(
        r'(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\s+'
        r'(\d{1,2})\s+(January|February|March|April|May|June|July|'
        r'August|September|October|November|December)\s+(\d{4})'
        r'((?:\s*\d{1,2}:\d{2})+)', re.I)

    for line in lines:
        if skip_patterns.match(line):
            continue
        # Check if this line is a date+time line
        dt_match = date_time_pat.match(line)
        if dt_match and current_film:
            date_key = parse_date(dt_match.group(2), dt_match.group(3), dt_match.group(4))
            times = re.findall(r'\b(\d{1,2}:\d{2})\b', dt_match.group(5))
            if date_key and times:
                for t in times:
                    schedule[date_key][current_film].add(t)
            continue
        # Otherwise treat as a potential film title if it looks right
        # Must be at least 3 chars, not all caps (skip genre labels), not a number
        if len(line) >= 3 and not re.match(r'^[\d:]+$', line):
            current_film = line

    return schedule

def render_schedule_js(schedule):
    lines = ["/* Auto-generated by scrape_schedule.py */",
             f"/* Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} */",
             "", "window.SCHEDULE = {"]
    for date_key in sorted(schedule.keys()):
        dt = datetime.strptime(date_key, "%Y-%m-%d")
        lines += ["", "  /* =======================",
                  f"   * {dt.strftime('%A')} {dt.day} {MONTH_NAMES[dt.month-1]} {dt.year}",
                  "   * ======================= */", f'  "{date_key}": [']
        for film, times_set in sorted(schedule[date_key].items()):
            ts = ", ".join(f'"{t}"' for t in sorted(times_set))
            lines.append(f'    {{ film: "{film}", times: [{ts}] }},')
        lines.append("  ],")
    lines += ["};", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    print("Fetching schedule from stationcinema.com...")
    html = fetch_page()
    schedule = extract_showtimes(html)
    if not schedule:
        print("WARNING: No schedule data found")
        raise SystemExit(1)
    total = sum(len(v) for v in schedule.values())
    print(f"Found {total} film/day combinations across {len(schedule)} days")
    output = render_schedule_js(schedule)
    with open("schedule.js", "w", encoding="utf-8") as f:
        f.write(output)
    print("schedule.js written successfully")
