var TMDB_OVERRIDES = window.TMDB_OVERRIDES || {};
var CUT_OFF_MINUTES_PAST = 15;
var PERIODIC_REFRESH_MS = 15 * 60 * 1000;
function getTodayKey(){ var n=new Date(); var y=n.getFullYear(), m=('0'+(n.getMonth()+1)).slice(-2), d=('0'+n.getDate()).slice(-2); return y+'-'+m+'-'+d; }
var SCHEDULE = window.SCHEDULE || {};
function tmdbPosterUrl(p,w){return p?("https://image.tmdb.org/t/p/w"+(w||342)+p):"";}
function tmdbFetch(path,params,cb){ try{ var key=window.TMDB_API_KEY||""; if(!key) return cb(null); var url=new URL("https://api.themoviedb.org/3"+path); url.searchParams.set("api_key",key); if(window.TMDB_LANG) url.searchParams.set("language",window.TMDB_LANG); for(var k in (params||{})){url.searchParams.set(k,params[k]);} fetch(url).then(function(r){ if(!r.ok) throw 0; return r.json(); }).then(function(j){ cb(j); }).catch(function(){ cb(null); }); }catch(e){ cb(null); } }
function gbCertFromReleaseDates(d){ try{ var arr=(d.release_dates && d.release_dates.results)||[]; var pick=arr.find(function(x){return x.iso_3166_1==="GB";})||arr.find(function(x){return x.iso_3166_1==="UK";})||arr.find(function(x){return x.iso_3166_1==="US";}); if(!pick||!pick.release_dates||!pick.release_dates.length) return null; var c=(pick.release_dates.find(function(r){return r.certification&&r.certification.trim();})||{}).certification||""; c=c.trim(); if(!c) return null; if(c==="12") c="12A"; return c; }catch(e){ return null; } }
function minutesToHm(mins){ if(!mins && mins!==0) return null; var h=Math.floor(mins/60), m=mins%60; return (h? (h+"h ") : "") + (m? (m+"m") : (h?"0m":"")); }
function normalizeTitle(t){ return String(t||"").replace(/\s*\([^)]*\)\s*$/,'').trim(); }
function lookupTitle(title, hint, cb){ function detailsById(id){ tmdbFetch("/movie/"+id, { append_to_response: "release_dates" }, function(d){ if(!d) return cb(null); var rating = gbCertFromReleaseDates(d); var runtime = (typeof d.runtime==="number"? d.runtime : null); cb({ title: d.title||title, overview: d.overview||"", poster_path: d.poster_path||null, runtime: runtime, rating: rating }); }); } if(hint && hint.id){ return detailsById(hint.id); } tmdbFetch("/search/movie", { query: title, include_adult:false, region:"GB" }, function(s){ if(!s||!s.results||!s.results.length) return cb(null); detailsById(s.results[0].id); }); }
function loadMetaCache(){ try{return JSON.parse(localStorage.getItem("tmdb_meta_v1")||"{}");}catch(e){return {};} }
function saveMetaCache(o){ try{localStorage.setItem("tmdb_meta_v1",JSON.stringify(o));}catch(e){} }
function ensureMetaForTitles(titles, done){ var cache=loadMetaCache(), out={}, i=0; function step(){ if(i>=titles.length){ saveMetaCache(cache); return done(out); } var orig=titles[i++]; var base=normalizeTitle(orig); var hint=TMDB_OVERRIDES[base] || TMDB_OVERRIDES[orig]; function store(m){ if(m){ cache[base]=m; out[base]=m; } step(); } if(hint && hint.id){ lookupTitle(base, hint, store); } else if(cache[base] && (cache[base].overview || cache[base].runtime || cache[base].rating)){ out[base]=cache[base]; step(); } else { lookupTitle(base, null, store); } } step(); }
function applyInfoScaleForSynopsis(text){ var len=(text||"").length, s=1.0; if(len<=200)s=1.15; else if(len<=300)s=0.90; else if(len<=600)s=0.85; else if(len<=900)s=0.80; else s=0.75; document.documentElement.style.setProperty('--infoScale',String(s)); }
function parseHM(hm){ var m=/^(\d{1,2}):(\d{2})$/.exec(String(hm||"").trim()); if(!m)return null; var n=new Date(); return new Date(n.getFullYear(),n.getMonth(),n.getDate(),+m[1],+m[2],0,0); }
function fmtCountdownLabel(d){ var mins=Math.round(d/60000); if(mins>=0){ var h=Math.floor(mins/60), m=mins%60; return h?("Departing in "+h+" h"+(m?" "+m+" m":"")):("Departing in "+m+" m"); } var a=Math.abs(mins),h2=Math.floor(a/60),m2=a%60; return h2?("Departed "+h2+" h"+(m2?" "+m2+" m":"")+" ago"):("Departed "+m2+" m ago"); }
function setContentScaleByCount(n){var panel=document.querySelector('.panel.today');var list=document.querySelector('.list');var row=document.querySelector('.row');if(!panel||!list||!row)return;var ps=getComputedStyle(panel);var padV=parseFloat(ps.paddingTop)+parseFloat(ps.paddingBottom);var availH=panel.clientHeight-padV;var gapStyle=getComputedStyle(list).gap;var gapPx=gapStyle&&gapStyle!=='normal'?parseFloat(gapStyle):0;var totalGap=gapPx*(n-1);var targetRowH=(availH-totalGap)/n;var prev=getComputedStyle(document.documentElement).getPropertyValue('--contentScale');document.documentElement.style.setProperty('--contentScale','1');requestAnimationFrame(function(){var baseRowH=row.getBoundingClientRect().height;document.documentElement.style.setProperty('--contentScale',prev);if(!baseRowH||baseRowH<5)return;var s=targetRowH/baseRowH;s=Math.max(0.8,Math.min(s,3.5));document.documentElement.style.setProperty('--contentScale',String(s));});}
function upcomingTimesToday(times){ var now=new Date(); var cutoffMs=CUT_OFF_MINUTES_PAST*60000; return (times||[]).map(function(t){ if(typeof t==="string") return { hm:t, sub:false }; return { hm:(t.hm||t.time), sub:!!t.sub }; }).map(function(x){ var dt=parseHM(x.hm); return {hm:x.hm, sub:x.sub, dt:dt}; }).filter(function(x){ return !x.dt || (x.dt>=new Date(now.getTime()-cutoffMs)); }).sort(function(a,b){ return !a.dt?1:!b.dt?-1:a.dt-b.dt; }); }
function buildDisplayTitle(film, meta){ var base = normalizeTitle(film); var m = meta[base] || {}; var display = film; if(typeof m.runtime === "number"){ var rt = minutesToHm(m.runtime); if(rt) display += " " + rt; } return display; }
function buildFilmRow(meta,film,timesArr){ var list=document.getElementById("today-list"); if(!list)return null; var row=document.createElement("div"); row.className="row"; var thumb=document.createElement("div"); thumb.className="thumb"; var img=document.createElement("img"); thumb.appendChild(img); var box=document.createElement("div"); box.className="film"; var title=document.createElement("div"); title.className="title"; title.textContent = buildDisplayTitle(film, meta); var times=document.createElement("div"); times.className="times"; var vis=upcomingTimesToday(timesArr); var now=new Date(); var cutoff=CUT_OFF_MINUTES_PAST*60000; var past=(timesArr||[]).map(function(t){return (typeof t==="string")?{hm:t}:{hm:(t.hm||t.time)};}).map(function(x){return parseHM(x.hm);}).filter(function(dt){return dt&&dt<=now;}).sort(function(a,b){return b-a;}); if(past.length){ try{ row.dataset.lastStart=past[0].toISOString(); }catch(e){} } var nextOrRecent=null; vis.forEach(function(x){ if(!x.dt)return; var tooOld=(now-x.dt)>cutoff; if(tooOld)return; var badge=document.createElement("span"); badge.className="badge"; if(x.sub){ badge.classList.add("sub"); badge.innerHTML=x.hm+' <span class="icon">\u00c3\u0083\u00c2\u00b0\u00c3\u0082\u00c2\u009f\u00c3\u0082\u00c2\u008e\u00c3\u0082\u00c2\u009e\u00c3\u0083\u00c2\u00af\u00c3\u0082\u00c2\u00b8\u00c3\u0082\u00c2\u008f<\/span> SUB'; } else { badge.textContent=x.hm; } if(x.dt && x.dt<=now) badge.classList.add("past"); times.appendChild(badge); if(!nextOrRecent) nextOrRecent=x.dt; }); var c=document.createElement("span"); c.className="count-inline"; if(nextOrRecent){ c.dataset.countdown=nextOrRecent.toTimeString().slice(0,5); var delta=nextOrRecent-now; c.textContent="\u2022 "+fmtCountdownLabel(delta); c.classList.add(delta>=0?"departing":"departed"); } times.appendChild(c); var base = normalizeTitle(film); if(meta[base] && meta[base].poster_path) img.src=tmdbPosterUrl(meta[base].poster_path,185); else img.remove(); box.appendChild(title); box.appendChild(times); row.appendChild(thumb); row.appendChild(box); if(!nextOrRecent && !row.dataset.lastStart) return null; return row; }
function updateInlineCountdowns(){ var now=new Date(); var cutoff=CUT_OFF_MINUTES_PAST*60000; Array.prototype.forEach.call(document.querySelectorAll('.row'),function(row){ var cnt=row.querySelector('.count-inline'); var badges=row.querySelectorAll('.times .badge'); var should=false; if(badges&&badges.length)should=true; if(cnt&&cnt.dataset.countdown){ var hm=cnt.dataset.countdown; var parts=hm.split(':');var H=parseInt(parts[0],10),M=parseInt(parts[1],10); var target=new Date(now.getFullYear(),now.getMonth(),now.getDate(),H,M,0,0); var delta=target-now; if(delta>=-cutoff){ cnt.textContent="\u2022 "+fmtCountdownLabel(delta); cnt.classList.remove("departing","departed"); cnt.classList.add(delta>=0?"departing":"departed"); should=true; } } if(!should){ var lastIso=row.dataset.lastStart; if(lastIso){ var last=new Date(lastIso); if(now-last<=cutoff) should=true; } } row.style.display=should?'':'none'; }); requestAnimationFrame(function(){setTimeout(updateInlineCountdowns,1000);}); }
function startInfoCycleWith(meta,list){ if(!list||!list.length)return; var i=0; var t=document.getElementById("info-title"), b=document.getElementById("info-body"), p=document.getElementById("info-poster"); function show(){ var key=list[i%list.length], base=normalizeTitle(key), m=meta[base]||{}; t.textContent=m.title||key; b.textContent=m.overview||"Enjoy the show!"; applyInfoScaleForSynopsis(b.textContent); if(m.poster_path){ p.src=tmdbPosterUrl(m.poster_path,342); p.style.display=""; } else { p.style.display="none"; } } show(); if(window.__infoTimer)clearInterval(window.__infoTimer); window.__infoTimer=setInterval(function(){i=(i+1)%list.length;show();},20000); }
function startClock(){ var t=document.getElementById("clock-time"), d=document.getElementById("clock-date"); function r(){ var n=new Date(); t.textContent=n.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"}); d.textContent=n.toLocaleDateString("en-GB",{weekday:"long",day:"2-digit",month:"short",year:"numeric"}); } r(); setInterval(r,1000); }
function startPeriodicRefresh(){ setInterval(function(){ location.reload(true); }, PERIODIC_REFRESH_MS); }
function ensureMetaForTodayAndRender(){ var key=getTodayKey(); var sched=(window.SCHEDULE||SCHEDULE||{}); var films=sched[key]||[]; var titles = Array.from(new Set(films.map(function(f){ return normalizeTitle(f.film); }))); ensureMetaForTitles(titles,function(meta){ var list=document.getElementById("today-list"); list.textContent=""; var any=false, cycle=[]; films.forEach(function(f){ var row=buildFilmRow(meta, f.film, (f.times||[])); if(row){ list.appendChild(row); any=true; cycle.push(f.film); } }); if(!any){ var n=document.createElement("div"); n.className="badge"; var schedKeys = Object.keys(window.SCHEDULE||SCHEDULE||{}); n.textContent="No listings for today ("+key+")."; list.appendChild(n); if(schedKeys.length){ var d=document.createElement("div"); d.className="small-note"; d.textContent="Schedule loaded with "+schedKeys.length+" day(s)."; list.appendChild(d); } } setContentScaleByCount(cycle.length); startInfoCycleWith(meta, cycle); }); }
window.addEventListener("DOMContentLoaded",function(){ startClock(); startPeriodicRefresh(); ensureMetaForTodayAndRender(); updateInlineCountdowns(); });